spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: task_manager_admin
    password: admin_123123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.yourcompany: DEBUG

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173
  jwt:
    secret: 932e02323195cd1011338838bcd6008b49baa5bfb930ea29d412c53139c1f915
  admin:
    seed-enabled: true
    name: Admin
    email: admin@example.com
    password: AdminPass123!

server:
  port: 8088
