spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: ${DB_USERNAME:task_manager_admin}
    password: ${DB_PASSWORD:admin_123123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.yourcompany: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:932e02323195cd1011338838bcd6008b49baa5bfb930ea29d412c53139c1f915}
  admin:
    seed-enabled: true
    name: ${ADMIN_NAME:Admin}
    email: ${ADMIN_EMAIL:admin@example.com}
    password: ${ADMIN_PASSWORD:AdminPass123!}
